name: dalai
description: El Design System ha de reflectir els valors i objectius de CityXerpa com a empresa.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  substring_highlight: any
  shimmer: any
  dotted_line: any
  auto_size_text: any
  url_launcher: any
  map_launcher: any
  geolocator: any
  cached_network_image: any
  lottie: any
  flutter_html: any
  latlng: any
  flutter_vibrate: any
  flutter_slidable: any
  custom_sliding_segmented_control: any
  loading_animation_widget: any
  cityxerpa_icons:
    git:
      url: https://gitlab.com/dribba-labs/cityxerpa/cityxerpa-icons.git
  country_flags: ^2.1.0
  flutter_svg: ^2.0.7
  palette_generator: any
  soundpool: any
  calendar_date_picker2: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/placeholders/placeholder_anything.jpg
    - lib/assets/images/placeholders/placeholder_courier.jpg
    - lib/assets/images/placeholders/placeholder_experiences.jpg
    - lib/assets/animations/ax_error_data.json
    - lib/assets/animations/ax_payment.json
    - lib/assets/animations/ax_error_generic.json
    - lib/assets/animations/ax_tracking_delivering.json
    - lib/assets/animations/ax_error_map.json
    - lib/assets/animations/ax_tracking_dropoff.json
    - lib/assets/animations/ax_error_search.json
    - lib/assets/animations/ax_tracking_ongoing_delivery.json
    - lib/assets/animations/ax_error_update.json
    - lib/assets/animations/ax_tracking_ongoing_market.json
    - lib/assets/animations/ax_error_working.json
    - lib/assets/animations/ax_tracking_ongoing_super.json
    - lib/assets/animations/ax_order_cancel.json
    - lib/assets/animations/ax_tracking_pickup.json
    - lib/assets/animations/ax_order_delivered.json
    - lib/assets/animations/ax_tracking_queued.json
#    - lib/assets/images/lama-ui-icon.png
#    - lib/assets/fonts/metropolis/regular.otf
#    - lib/assets/fonts/metropolis/semibold.otf
#    - lib/assets/fonts/metropolis/bold.otf

  fonts:
    - family: metropolis
      fonts:
        - asset: lib/assets/fonts/metropolis/regular.otf
          weight: 400
        - asset: lib/assets/fonts/metropolis/semibold.otf
          weight: 600
        - asset: lib/assets/fonts/metropolis/bold.otf
          weight: 700
